### PR TITLE
Fix check of availability for OpenMP

### PR DESCRIPTION
**Pull request by p-otto**

### CODE REVIEW

**Comment by kateyy** [comment]
`OpenMP_FOUND` is not available in CMake 3.6 and earlier, look [here](https://cmake.org/cmake/help/v3.6/module/FindOpenMP.html?highlight=OPENMP_FOUND). The old versions set `OPENMP_FOUND`, and CMake variable names are case-sensitive. Does the current check really fail on CMake 3.7 and above?

**Comment by p-otto** [comment]
Yes, on MacOS with CMake 3.9.4 `OpenMP_FOUND` is set instead of `OPENMP_FOUND`.

Looks like CMake (accidentally?) broke backward compatibility as of version 3.9: https://cmake.org/cmake/help/v3.9/module/FindOpenMP.html

@cgcostume @scheibel Any ideas on how to handle this?

**Comment by scheibel** [comment]
Seems like we have to check for both unset `OpenMP_FOUND` and `OPENMP_FOUND`. If one of both is set, OpenMP is most likely found.
Does this also affect other variables like `OpenMP_CXX_FLAGS`?

**Comment by p-otto** [comment]
OpenMP_CXX_FLAGS and other variables were not changed.
I pushed a fix for old CMake versions, please review again.

**Pull request merged**
